---
sidebar: sidebar 
permalink: task-restore-oracle-data.html 
keywords: restore, Azure, Amazon Web services, Oracle database 
summary: 您可以將Oracle資料庫從雲端還原至內部部署SnapCenter 的支援服務器。 
---
= 還原Oracle資料庫
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您只能將Oracle資料庫還原至相同SnapCenter 的SVM主機、相同的SVM或相同的資料庫主機。對於RAC資料庫、資料將還原至建立備份的內部部署節點。

僅支援具有控制檔還原的完整資料庫。如果檔案記錄未出現在檔案管理系統中、您應該指定包含還原所需的歸檔記錄的位置。

*步驟*

. 在Cloud Manager UI中、按一下*備份與還原*>*應用程式*。
. 在*篩選條件*欄位中、選取篩選條件*類型*、然後從下拉式清單中選取* Oracle*。
. 按一下您要還原之資料庫的*檢視詳細資料*、然後按一下*還原*。
. 在「還原類型」頁面上、執行下列動作：
+
.. 如果您想要還原控制檔及完整資料庫、請選取* Control files*。
.. 如果需要還原與還原*、請選取*變更資料庫狀態、將資料庫狀態變更為執行還原與還原作業所需的狀態。
+
從高到低的資料庫狀態會開啟、掛載、啟動和關機。如果資料庫處於較高的狀態、但必須將狀態變更為較低的狀態、才能執行還原作業、則必須選取此核取方塊。如果資料庫處於較低的狀態、但必須將狀態變更為較高的狀態才能執行還原作業、即使您未選取此核取方塊、資料庫狀態也會自動變更。

+
如果資料庫處於開啟狀態、而還原資料庫需要處於掛載狀態、則只有在選取此核取方塊時、資料庫狀態才會變更。



. 在「恢復範圍」頁面上、執行下列動作：
+
.. 指定恢復範圍。
+
|===
| 如果您... | 執行此動作... 


 a| 
想要恢復到最後一筆交易
 a| 
選取*所有記錄*。



 a| 
想要恢復至特定的系統變更編號（SCN）
 a| 
選擇*直到SCN（系統變更編號）*。



 a| 
想要恢復到特定的資料和時間
 a| 
選擇*日期和時間*。

您必須指定資料庫主機時區的日期和時間。



 a| 
不想恢復
 a| 
選擇*無恢復*。



 a| 
想要指定任何外部歸檔記錄位置
 a| 
如果檔案記錄未出現在檔案管理系統中、您應該指定包含還原所需的歸檔記錄的位置。

|===
.. 如果您要在恢復後開啟資料庫、請選取此核取方塊。
+
在RAC設定中、只有用於還原的RAC執行個體會在還原後開啟。



. 檢閱詳細資料、然後按一下*還原*。

